const FORM_CONST = {
  76: [
    {
      id: 1,
      title: '维护预备',
      items: [
        {id: 'IsSelectLog', title: '查询日志 7d'},
        {id: 'IsCheckHC', title: '检查耗材 7d'},
      ],
    },
    {
      id: 2,
      title: '辅助设备检查',
      items: [
        {id: 'ZFWS', title: '站房卫生 7d'},
        {id: 'ZFMCMFX', title: '站房门窗的密封性检查 7d'},
        {id: 'GDXT', title: '供电系统（稳压、UPS 等）7d'},
        {id: 'SNWSD', title: '室内温湿度 7d'},
        {id: 'KT', title: '空调 7d'},
        {id: 'KQYSJYL', title: '空气压缩机压力 7d'},
        {id: 'YSJPS', title: '压缩机排水 7d'},
      ],
    },
    {
      id: 3,
      title: '气态污染物监测设备检查',
      items: [
        {id: 'TTGLJRWDJC', title: '探头、管路加热温度检查 7d'},
        {id: 'CYXTLL', title: '采样系统流量 7d'},
        {id: 'FCGLZZFMJC', title: '反吹过滤装置、阀门检查 7d'},
        {id: 'SDFCJC', title: '手动反吹检查 7d'},
        {id: 'CYBLL', title: '采样泵流量 7d'},
        {id: 'ZLQWD', title: '制冷器温度 7d'},
        {id: 'PSXTGLLNSJC', title: '排水系统、管路冷凝水检查 7d'},
        {id: 'KQGLQ', title: '空气过滤器 7d'},
        {id: 'BQYXQGPYLJC', title: '标气有效期、钢瓶压力检查 7d'},
        {id: 'YQFXYZTJC', title: '烟气分析仪状态检查 7d'},
        {id: 'YQFXYJZ', title: '烟气分析仪校准 15d'},
        {id: 'CLSJJC', title: '测量数据检查 7d'},
        {id: 'QXTJZ', title: '全系统校准 90d'},
        {id: 'XTJY', title: '系统校验 90d或180d'},
      ],
    },
    {
      id: 4,
      title: '流速监测系统检查',
      items: [
        {id: 'FCZZ', title: '反吹装置 30d'},
        {id: 'LSLLYDYL', title: '流速、流量、烟道压力测量数据 7d'},
        {id: 'JCPTGFCGL', title: '检查皮托管的反吹管路、控制阀等否正常 7d'},
      ],
    },
    {
      id: 5,
      title: '烟气监测系统',
      items: [
        {id: 'TTLXCYG', title: '探头滤芯、采样管、伴热管是否堵塞 7d'},
        {
          id: 'CYTTFCSFZC',
          title: '采样探头反吹是否正常，电磁阀、反吹气源 7d',
        },
        {
          id: 'FXYDJHZZGL',
          title: '分析仪的净化装置管路、风机、过滤器、风量 【直接测量法 】7d',
        },
        {id: 'XFJGZJGQ', title: '吸附剂、干燥剂是否过期 7d'},
        {id: 'TTGLJRSFZC', title: '探头管路加热是否正常 【完全抽取法】 7d'},
        {id: 'XSTTKZQ', title: '稀释探头控制器 【稀释采样法】 7d'},
        {id: 'LNQGZWD', title: '冷凝器工作温度 【完全抽取原理设备】7d'},
        {
          id: 'XSQYL',
          title: '稀释气压力、真空度压力【稀释采样原理设备】7d',
        },
        {id: 'JCSJSFZC', title: '监测数据是否正常，分析仪校准 7d'},
        {id: 'BQYXQ', title: '标气有效期、剩余量（压力） 7d'},
        {
          id: 'ZHQGZ',
          title: '（二氧化氮→一氧化氮）转换器工作 7d',
          type: 'input',
        },
        {id: 'CYGLQMXJC', title: '采样管路气密性检查 30d', type: 'input'},
        {
          id: 'QXCYTTGLZZ',
          title: '清洗采样探头、过滤装置、采样泵 30d',
          type: 'input',
        },
        {id: 'YQJC_Remark', title: '情况说明', type: 'textarea'},
      ],
    },
    {
      id: 6,
      title: '颗粒物监测系统',
      items: [
        {id: 'GFJKQGLQJC', title: '鼓风机、空气过滤器检查 30d'},
        {id: 'JCSJJC', title: '监测数据检查 7d'},
        {id: 'JZ', title: '校准 30d'},
        {id: 'DSCYXTGZ', title: '等速采样系统工作 7d'},
        {id: 'KLWJCSJ', title: '颗粒物监测数据 7d'},
        {id: 'ZDDHCSYQK', title: '纸带等耗材使用情况 7d'},
        {id: 'KLWGKJGZZT', title: '颗粒物工控机工作状态，有无报警 7d'},
        {id: 'GFJFGKQGLQ', title: '鼓风机、风管、空气过滤器等部件工作 7d'},
        {id: 'GFJFGGLZZSFZC', title: '鼓风机、风管、过滤装置是否正常'},
        {id: 'FCQYYLSFZC', title: '反吹气源压力是否正常'},
        {id: 'YLSFZJ', title: '压力是否在0.4 MPa～0.6 MPa 之间'},
        {id: 'GLBRZZ', title: '管路、伴热装置'},
        {id: 'CCYZDSFWHCZ', title: '查采样纸带是否完好充足（称重法）'},
        {id: 'CBSFGZYWCD', title: '尘斑是否干燥，有无重叠（称重法）'},
        {
          id: 'MSSTZSBYYC',
          title: '每30天至少按照说明书保养一次颗粒物 CEMS 30d',
          type: 'input',
        },
        {id: 'FXYCYXTQXWH', title: '采样系统清洗维护 30d', type: 'input'},
        {
          id: 'KLWJC_Remark',
          title: '情况说明',
          type: 'textarea',
          type: 'textarea',
        },
      ],
    },
    {
      id: 7,
      title: '皮托管法',
      items: [
        {id: 'YLCDGXSFZC', title: '压力传导管线是否正常'},
        {id: 'YLBSQYXSFZC', title: '压力变送器运行是否正常'},
        {id: 'PTGQKSFZC', title: '皮托管情况是否正常'},
        {id: 'FCGLKZFSFZC', title: '反吹管路、控制阀是否正常'},
      ],
    },
    {
      id: 8,
      title: '热平衡法',
      items: [{id: 'TTWDTZQKSFZC', title: '探头温度探针情况是否正常'}],
    },
    {
      id: 9,
      title: '超声波法',
      items: [
        {id: 'GFJLJGLGLZZQK', title: '鼓风机、连接管路、过滤装置情况'},
        {id: 'FLQKSFZC', title: '法兰情况是否正常'},
        {id: 'WJFTTWZSFCXPY', title: '涡街法探头位置是否出现偏移'},
        {id: 'CSBNLZHQTGQK', title: '超声波能量转换器套管情况'},
        {id: 'CSBNLZHQBMQK', title: '超声波能量转换器表面情况'},
        {id: 'CSBNLZHQXFPSSFZC', title: '超声波能量转换器下方排水是否正常'},
        {id: 'CLCGQ', title: '测量传感器 30d', type: 'input'},
        {id: 'TTJC', title: '探头检查 90d', type: 'input'},
        {id: 'CSBF_Remark', title: '情况描述', type: 'textarea'},
      ],
    },
    {
      id: 10,
      title: '其它烟气监测参数',
      items: [
        {id: 'WDCLZSFZC', title: '温度测量值是否正常 7d'},
        {id: 'SDCLZSFZC', title: '湿度测量值是否正常 7d'},
        {id: 'SDYTRKQDQ', title: '湿度仪通入空气/氮气情况'},
        {id: 'SDYGLJLJ', title: '湿度仪管路及连接情况'},
        {id: 'SDYGLSFMF', title: '湿度仪管路是否密封'},
        {id: 'SDYSFYJSJHJG', title: '湿度仪是否有积水、积灰、积垢'},
        {id: 'YHLCLZSFZC', title: '氧量测量值是否正常 7d'},
        {id: 'YHLCLSJ', title: '氧含量测量数据 7d'},
        {id: 'WDCLSJ', title: '温度测量数据 7d'},
        {id: 'SDCLSJ', title: '湿度测量数据 7d'},
        {id: 'Other_Remark', title: '情况说明', type: 'textarea'},
      ],
    },
    {
      id: 11,
      title: '数据采集传输装置',
      items: [
        {id: 'GTXXDLJSFSD', title: '各通讯线的连接是否松动 7d'},
        {id: 'CSSBDY', title: '传输设备电源 7d'},
        {id: 'SJCSKSFZC', title: '数据传输卡是否正常 7d'},
        {
          id: 'FXYGKJSJCJCSY',
          title: '分析仪、工控机、数据采集传输仪上的数据 是否一致（7d）',
        },
        {id: 'SJCJCSZZ_Remark', title: '情况说明', type: 'textarea'},
      ],
    },
    {
      id: 12,
      title: '其他辅助设备',
      items: [
        {id: 'KQYSXTSFZC', title: '空气压缩系统是否正常 7d'},
        {id: 'FSQCQZZZDSSFFD', title: '分水器、储气装置中的水是否放掉 7d'},
        {id: 'SNDWDSDSFZC', title: '室内的温度、湿度是否正常 7d'},
        {id: 'FLSSJC', title: '防雷设施检查 7d'},
        {id: 'XFSS', title: '消防设施 7d'},
        {id: 'KTGZQK', title: '空调工作情况 7d'},
        {id: 'FXZFDMCSFMF', title: '分析站房的门窗是否密封 7d'},
        {id: 'ZFQJWS', title: '站房清洁卫生 7d'},
        {
          id: 'OtherFZ_Remark',
          title: '其他辅助设备-情况说明',
          type: 'textarea',
        },
      ],
    },
    {
      id: 13,
      title: '站房全景照片（室内与室外）',
      items: [{id: 'ZFQJZP', title: '站房全景照片（室内）', type: 'upload'}],
    },
    {
      id: 14,
      title: '维护各个单元工作过程照片',
      items: [
        {
          id: 'WHGGDYGZGCZP',
          title: '维护各个单元工作过程照片',
          type: 'upload',
        },
      ],
    },
    {
      id: 15,
      title: '异常情况处理记录',
      items: [
        {
          id: 'ExceptionRecord',
          title: '异常情况处理记录',
          type: 'textarea',
        },
      ],
    },
    {
      id: 16,
      title: '巡检人员签字',
      items: [{id: 'XJRYQZ', title: '签名', type: 'signature'}],
    },
  ],
  77: [
    {
      id: 1,
      title: '维护预备',
      items: [
        {id: 'IsSelectLog', title: '查询日志 7d'},
        {id: 'IsCheckHC', title: '检查耗材 7d'},
      ],
    },
    {
      id: 2,
      title: '辅助设备检查',
      items: [
        {id: 'ZFWS', title: '站房卫生 7d'},
        {id: 'ZFMCMFX', title: '站房门窗的密封性检查 7d'},
        {id: 'GDXT', title: '供电系统（稳压、UPS 等）7d'},
        {id: 'SNWSD', title: '室内温湿度 7d'},
        {id: 'KT', title: '空调 7d'},
        {id: 'KQYSJYL', title: '空气压缩机压力 7d'},
        {id: 'YSJPS', title: '压缩机排水 7d'},
      ],
    },
    {
      id: 3,
      title: '气态污染物监测设备检查',
      items: [
        {id: 'JRZZWDJC', title: '加热装置温度检查 7d'},
        {id: 'XSQYLZKDYL', title: '稀释气压力、真空度压力 7d'},
        {id: 'XFJGZJ', title: '吸附剂、干燥剂 7d'},
        {id: 'XSTTKZQ', title: '稀释探头控制器 7d'},
        {id: 'FCGLZZFMJC', title: '反吹过滤装置、阀门检查 7d'},
        {id: 'SDFCJC', title: '手动反吹检查 7d'},
        {id: 'BQYXQGPYL', title: '标气有效期、钢瓶压力检查 7d'},
        {id: 'FXYCYBLLJC', title: '分析仪采样泵流量检查 7d'},
        {id: 'FXYHC', title: '分析仪耗材 7d'},
        {id: 'FXYZT', title: '分析仪状态 7d'},
        {id: 'FXYJZ', title: '分析仪校准 15d'},
        {id: 'CLSJJC', title: '测量数据检查 7d'},
        {id: 'QXTJZ', title: '全系统校准 90d'},
        {id: 'XTJY', title: '系统校验 90d或180d'},
      ],
    },
    {
      id: 4,
      title: '流速监测系统检查',
      items: [
        {id: 'FCZZ', title: '反吹装置 30d'},
        {id: 'LSLLYDYL', title: '流速、流量、烟道压力测量数据 7d'},
        {id: 'JCPTGFCGL', title: '检查皮托管的反吹管路、控制阀等否正常 7d'},
      ],
    },
    {
      id: 5,
      title: '烟尘监测系统检查',
      items: [
        {id: 'TTLXCYG', title: '探头滤芯、采样管、伴热管是否堵塞 7d'},
        {id: 'CYTTFCSFZC', title: '采样探头反吹是否正常，电磁阀、反吹气源 7d'},
        {
          id: 'FXYDJHZZGL',
          title: '分析仪的净化装置管路、风机、过滤器、风量 【直接测量法 】7d',
        },
        {id: 'TTGLJRSFZC', title: '探头管路加热是否正常 【完全抽取法】 7d'},
        {id: 'LNQGZWD', title: '冷凝器工作温度 【完全抽取原理设备】7d'},
        {id: 'JCSJSFZC', title: '监测数据是否正常，分析仪校准 7d'},
        {id: 'ZHQGZ', title: '（二氧化氮→一氧化氮）转换器工作 7d'},
        {
          id: 'ZHQZHXL',
          title: '（二氧化氮→一氧化氮）转换器转换效率≥95 % 30d',
          type: 'input',
        },
        {id: 'CYGLQMXJC', title: '采样管路气密性检查 30d', type: 'input'},
        {
          id: 'QXCYTTGLZZ',
          title: '清洗采样探头、过滤装置、采样泵 30d',
          type: 'input',
        },
        {id: 'YQJC_Remark', title: '情况说明', type: 'textarea'},
      ],
    },
    {
      id: 6,
      title: '颗粒物监测系统检查',
      items: [
        {id: 'GFJKQGLQJC', title: '鼓风机、空气过滤器检查 30d'},
        {id: 'FXYGLJC', title: '分析仪的光路检查 30d'},
        {id: 'JCSJJC', title: '监测数据检查 7d'},
        {id: 'JZ', title: '校准 30d'},
        {id: 'DSCYXTGZ', title: '等速采样系统工作 7d'},
        {id: 'KLWJCSJ', title: '颗粒物监测数据 7d'},
        {id: 'ZDDHCSYQK', title: '纸带等耗材使用情况 7d'},
        {id: 'KLWGKJGZZT', title: '颗粒物工控机工作状态，有无报警 7d'},
        {id: 'GFJFGKQGLQ', title: '鼓风机、风管、空气过滤器等部件工作 7d'},
        {id: 'GFJFGGLZZSFZC', title: '鼓风机、风管、过滤装置是否正常'},
        {id: 'FCQYYLSFZC', title: '反吹气源压力是否正常'},
        {id: 'YLSFZJ', title: '压力是否在0.4 MPa～0.6 MPa 之间'},
        {id: 'GLBRZZ', title: '管路、伴热装置'},
        {id: 'CCYZDSFWHCZ', title: '查采样纸带是否完好充足（称重法）'},
        {id: 'CBSFGZYWCD', title: '尘斑是否干燥，有无重叠（称重法）'},
        {
          id: 'MSSTZSBYYC',
          title: '每30天至少按照说明书保养一次颗粒物 CEMS 30d',
          type: 'input',
        },
        {id: 'FXYCYXTQXWH', title: '分析仪采样系统清洗维护 30d', type: 'input'},
        {id: 'FXYDGLJCQX', title: '分析仪的光路检查、清洗 30d', type: 'input'},
        {
          id: 'KLWJC_Remark',
          title: '颗粒物监测系统-情况说明',
          type: 'textarea',
        },
      ],
    },
    {
      id: 7,
      title: '皮托管法',
      items: [
        {id: 'YLCDGXSFZC', title: '压力传导管线是否正常'},
        {id: 'YLBSQYXSFZC', title: '压力变送器运行是否正常'},
        {id: 'PTGQKSFZC', title: '皮托管情况是否正常'},
        {id: 'FCGLKZFSFZC', title: '反吹管路、控制阀是否正常'},
      ],
    },
    {
      id: 8,
      title: '热平衡法',
      items: [{id: 'TTWDTZQKSFZC', title: '探头温度探针情况是否正常'}],
    },
    {
      id: 9,
      title: '超声波法',
      items: [
        {id: 'GFJLJGLGLZZQK', title: '鼓风机、连接管路、过滤装置情况'},
        {id: 'FLQKSFZC', title: '法兰情况是否正常'},
        {id: 'WJFTTWZSFCXPY', title: '涡街法探头位置是否出现偏移'},
        {id: 'CSBNLZHQTGQK', title: '超声波能量转换器套管情况'},
        {id: 'CSBNLZHQBMQK', title: '超声波能量转换器表面情况'},
        {id: 'CSBNLZHQXFPSSFZC', title: '超声波能量转换器下方排水是否正常'},
        {id: 'CLCGQ', title: '测量传感器 30d', type: 'input'},
        {id: 'TTJC', title: '探头检查 90d', type: 'input'},
        {id: 'CSBF_Remark', title: '情况描述', type: 'textarea'},
      ],
    },
    {
      id: 10,
      title: '其它烟气监测参数',
      items: [
        {id: 'WDCLZSFZC', title: '温度测量值是否正常 7d'},
        {id: 'SDCLZSFZC', title: '湿度测量值是否正常 7d'},
        {id: 'SDYTRKQDQ', title: '湿度仪通入空气/氮气情况'},
        {id: 'SDYGLJLJ', title: '湿度仪管路及连接情况'},
        {id: 'SDYGLSFMF', title: '湿度仪管路是否密封'},
        {id: 'SDYSFYJSJHJG', title: '湿度仪是否有积水、积灰、积垢'},
        {id: 'YHLCLZSFZC', title: '氧量测量值是否正常 7d'},
        {id: 'YHLCLSJ', title: '氧含量测量数据检查 7d'},
        {id: 'WDCLSJ', title: '温度测量数据检查 7d'},
        {id: 'SDCLSJ', title: '湿度测量数据检查 7d'},
        {id: 'Other_Remark', title: '情况说明', type: 'textarea'},
      ],
    },
    {
      id: 11,
      title: '数据采集传输装置',
      items: [
        {id: 'GTXXDLJSFSD', title: '各通讯线的连接是否松动 7d'},
        {id: 'CSSBDY', title: '传输设备电源 7d'},
        {id: 'SJCSKSFZC', title: '数据传输卡是否正常 7d'},
        {
          id: 'FXYGKJSJCJCSY',
          title: '分析仪、工控机、数据采集传输仪上的数据是否一致（7d）',
        },
        {id: 'SJCJCSZZ_Remark', title: '情况说明', type: 'textarea'},
      ],
    },
    {
      id: 12,
      title: '其他辅助设备',
      items: [
        {id: 'KQYSXTSFZC', title: '空气压缩系统是否正常 7d'},
        {id: 'FSQCQZZZDSSFFD', title: '分水器、储气装置中的水是否放掉 7d'},
        {id: 'SNDWDSDSFZC', title: '室内的温度、湿度是否正常 7d'},
        {id: 'FLSSJC', title: '防雷设施检查 7d'},
        {id: 'XFSS', title: '消防设施 7d'},
        {id: 'KTGZQK', title: '空调工作情况 7d'},
        {id: 'FXZFDMCSFMF', title: '分析站房的门窗是否密封 7d'},
        {id: 'ZFQJWS', title: '站房清洁卫生 7d'},
        {id: 'OtherFZ_Remark', title: '情况说明', type: 'textarea'},
      ],
    },
    {
      id: 13,
      title: '站房全景照片（室内与室外）',
      items: [
        {id: 'ZFQJZP', title: '站房全景照片（室内与室外）', type: 'upload'},
      ],
    },
    {
      id: 14,
      title: '维护各个单元工作过程照片',
      items: [
        {id: 'WHGGDYGZGCZP', title: '维护各个单元工作过程照片', type: 'upload'},
      ],
    },
    {
      id: 15,
      title: '异常情况处理记录',
      items: [
        {id: 'ExceptionRecord', title: '异常情况处理记录', type: 'textarea'},
      ],
    },
    {
      id: 16,
      title: '巡检人员签字',
      items: [{id: 'XJRYQZ', title: '签名', type: 'signature'}],
    },
  ],
  78: [
    {
      id: 1,
      title: '维护预备',
      items: [
        {id: 'IsSelectLog', title: '查询日志 7d'},
        {id: 'IsCheckHC', title: '检查耗材 7d'},
      ],
    },
    {
      id: 2,
      title: '辅助设备检查',
      items: [
        {id: 'ZFWS', title: '站房卫生 7d'},
        {id: 'ZFMCMFX', title: '站房门窗的密封性检查 7d'},
        {id: 'GDXT', title: '供电系统（稳压、UPS 等） 7d'},
        {id: 'SNWSD', title: '室内温湿度 7d'},
        {id: 'KT', title: '空调 7d'},
        {id: 'KQYSJYL', title: '空气压缩机压力 7d'},
        {id: 'YSJPS', title: '压缩机排水 7d'},
      ],
    },
    {
      id: 3,
      title: '气态污染物监测设备检查',
      items: [
        {id: 'JHFJJC', title: '净化风机检查 7d'},
        {id: 'GLQJGLJC', title: '过滤器及管路检查 7d'},
        {id: 'BQYXQGPYL', title: '标气的有效期、钢瓶压力检查 7d'},
        {id: 'CLSJJC', title: '测量数据检查 7d'},
        {id: 'FXYZT', title: '分析仪状态 7d'},
        {id: 'CLTT', title: '测量探头 30d'},
        {id: 'FXYJZ', title: '分析仪校准 30d'},
        {id: 'XTJY', title: '系统校验 90d或180d'},
      ],
    },
    {
      id: 4,
      title: '流速监测系统检查',
      items: [
        {id: 'FCZZ', title: '反吹装置 30d'},
        {id: 'LSLLYDYL', title: '流速、流量、烟道压力测量数据 7d'},
      ],
    },
    {
      id: 5,
      title: '烟气监测系统检查',
      items: [
        {id: 'TTLXCYG', title: '探头滤芯、采样管、伴热管是否堵塞 7d'},
        {id: 'CYTTFCSFZC', title: '采样探头反吹是否正常，电磁阀、反吹气源 7d'},
        {
          id: 'FXYDJHZZGL',
          title: '分析仪的净化装置管路、风机、过滤器、风量 【直接测量法 】7d',
        },
        {id: 'XFJGZJGQ', title: '吸附剂、干燥剂是否过期 7d'},
        {id: 'TTGLJRSFZC', title: '探头管路加热是否正常 【完全抽取法】 7d'},
        {id: 'XSTTKZQ', title: '稀释探头控制器 【稀释采样法】 7d'},
        {id: 'LNQGZWD', title: '冷凝器工作温度 【完全抽取原理设备】7d'},
        {id: 'XSQYL', title: '稀释气压力、真空度压力【稀释采样原理设备】7d'},
        {id: 'JCSJSFZC', title: '监测数据是否正常，分析仪校准 7d'},
        {id: 'ZHQGZ', title: '（二氧化氮→一氧化氮）转换器工作 7d'},
        {
          id: 'ZHQZHXL',
          title: '（二氧化氮→一氧化氮）转换器转换效率≥95 % 30d',
          type: 'input',
        },
        {id: 'CYGLQMXJC', title: '采样管路气密性检查 30d', type: 'input'},
        {
          id: 'QXCYTTGLZZ',
          title: '清洗采样探头、过滤装置、采样泵 30d',
          type: 'input',
        },
        {id: 'YQJC_Remark', title: '情况说明', type: 'textarea'},
      ],
    },
    {
      id: 6,
      title: '颗粒物监测系统检查',
      items: [
        {id: 'JCSJJC', title: '监测数据检查 7d'},
        {id: 'GFJKQGLQJC', title: '鼓风机、空气过滤器检查 30d'},
        {id: 'FXYGLJC', title: '分析仪的光路检查 30d'},
        {id: 'JZ', title: '校准 30d', type: 'input'},
        {id: 'DSCYXTGZ', title: '等速采样系统工作 7d'},
        {id: 'KLWJCSJ', title: '颗粒物监测数据 7d'},
        {id: 'ZDDHCSYQK', title: '纸带等耗材使用情况 7d'},
        {id: 'KLWGKJGZZT', title: '颗粒物工控机工作状态，有无报警 7d'},
        {id: 'GFJFGKQGLQ', title: '鼓风机、风管、空气过滤器等部件工作 7d'},
        {id: 'GFJFGGLZZSFZC', title: '鼓风机、风管、过滤装置是否正常'},
        {id: 'FCQYYLSFZC', title: '反吹气源压力是否正常'},
        {id: 'YLSFZJ', title: '压力是否在0.4 MPa～0.6 MPa 之间'},
        {id: 'CCYZDSFWHCZ', title: '查采样纸带是否完好充足（称重法）'},
        {id: 'CBSFGZYWCD', title: '尘斑是否干燥，有无重叠（称重法）'},
        {
          id: 'MSSTZSBYYC',
          title: '每30天至少按照说明书保养一次颗粒物 CEMS 30d',
          type: 'input',
        },
        {id: 'FXYCYXTQXWH', title: '分析仪采样系统清洗维护 30d', type: 'input'},
        {id: 'FXYDGLJCQX', title: '分析仪的光路检查、清洗 30d', type: 'input'},
        {
          id: 'KLWJC_Remark',
          title: '颗粒物监测系统-情况说明',
          type: 'textarea',
        },
      ],
    },
    {
      id: 7,
      title: '皮托管法',
      items: [
        {id: 'YLCDGXSFZC', title: '压力传导管线是否正常'},
        {id: 'YLBSQYXSFZC', title: '压力变送器运行是否正常'},
        {id: 'PTGQKSFZC', title: '皮托管情况是否正常'},
        {id: 'FCGLKZFSFZC', title: '反吹管路、控制阀是否正常'},
      ],
    },
    {
      id: 8,
      title: '热平衡法',
      items: [{id: 'TTWDTZQKSFZC', title: '探头温度探针情况是否正常'}],
    },
    {
      id: 9,
      title: '超声波法',
      items: [
        {id: 'GFJLJGLGLZZQK', title: '鼓风机、连接管路、过滤装置情况'},
        {id: 'FLQKSFZC', title: '法兰情况是否正常'},
        {id: 'WJFTTWZSFCXPY', title: '涡街法探头位置是否出现偏移'},
        {id: 'CSBNLZHQTGQK', title: '超声波能量转换器套管情况'},
        {id: 'CSBNLZHQBMQK', title: '超声波能量转换器表面情况'},
        {id: 'CSBNLZHQXFPSSFZC', title: '超声波能量转换器下方排水是否正常'},
        {id: 'CLCGQ', title: '测量传感器 30d', type: 'input'},
        {id: 'TTJC', title: '探头检查 90d', type: 'input'},
        {id: 'CSBF_Remark', title: '情况描述', type: 'textarea'},
      ],
    },
    {
      id: 10,
      title: '其他烟气监测参数',
      items: [
        {id: 'WDCLZSFZC', title: '温度测量值是否正常 7d'},
        {id: 'SDCLZSFZC', title: '湿度测量值是否正常 7d'},
        {id: 'SDYTRKQDQ', title: '湿度仪通入空气/氮气情况'},
        {id: 'SDYGLJLJ', title: '湿度仪管路及连接情况'},
        {id: 'SDYGLSFMF', title: '湿度仪管路是否密封'},
        {id: 'SDYSFYJSJHJG', title: '湿度仪是否有积水、积灰、积垢'},
        {id: 'YHLCLZSFZC', title: '氧量测量值是否正常 7d'},
        {id: 'YHLCLSJ', title: '氧含量测量数据检查 7d'},
        {id: 'WDCLSJ', title: '温度测量数据检查 7d'},
        {id: 'SDCLSJ', title: '湿度测量数据检查 7d'},
        {id: 'Other_Remark', title: '情况说明', type: 'textarea'},
      ],
    },
    {
      id: 11,
      title: '数据采集传输装置',
      items: [
        {id: 'GTXXDLJSFSD', title: '各通讯线的连接是否松动 7d'},
        {id: 'CSSBDY', title: '传输设备电源 7d'},
        {id: 'SJCSKSFZC', title: '数据传输卡是否正常 7d'},
        {
          id: 'FXYGKJSJCJCSY',
          title: '分析仪、工控机、数据采集传输仪上的数据是否一致（7d）',
        },
        {id: 'SJCJCSZZ_Remark', title: '情况说明', type: 'textarea'},
      ],
    },
    {
      id: 12,
      title: '其他辅助设备',
      items: [
        {id: 'KQYSXTSFZC', title: '空气压缩系统是否正常 7d'},
        {id: 'FSQCQZZZDSSFFD', title: '分水器、储气装置中的水是否放掉 7d'},
        {id: 'SNDWDSDSFZC', title: '室内的温度、湿度是否正常 7d'},
        {id: 'FLSSJC', title: '防雷设施检查 7d'},
        {id: 'XFSS', title: '消防设施 7d'},
        {id: 'KTGZQK', title: '空调工作情况 7d'},
        {id: 'FXZFDMCSFMF', title: '分析站房的门窗是否密封 7d'},
        {id: 'ZFQJWS', title: '站房清洁卫生 7d'},
        {id: 'OtherFZ_Remark', title: '情况说明', type: 'textarea'},
      ],
    },
    {
      id: 13,
      title: '站房全景照片（室内与室外）',
      items: [
        {id: 'ZFQJZP', title: '站房全景照片（室内与室外）', type: 'upload'},
      ],
    },
    {
      id: 14,
      title: '维护各个单元工作过程照片',
      items: [
        {id: 'WHGGDYGZGCZP', title: '维护各个单元工作过程照片', type: 'upload'},
      ],
    },
    {
      id: 15,
      title: '异常情况处理记录',
      items: [
        {id: 'ExceptionRecord', title: '异常情况处理记录', type: 'textarea'},
      ],
    },
    {
      id: 16,
      title: '巡检人员签字',
      items: [{id: 'XJRYQZ', title: '签名', type: 'signature'}],
    },
  ],
};

export default FORM_CONST;
